### ISSUE TITLE
charles_status meaning?

### ISSUE THREAD

**Issue by campbellC** [mandrean/har-rs#13]
Hi there,

Nice crate, thanks for writing! I'm just picking it up for a project of mine but I'm unsure about one thing. What's the meaning of the `charles_status` field on `Response`? I'm assuming this is related to [Charles](https://www.charlesproxy.com/) - it feels strange to have a field in a generic library crate that's tied to a specific piece of software like that so just wanted to understand. Do you have a specific RFC that describes the format you are coding to? The link on the README goes to wikipedia, which links to an RFC that says 'DO NOT USE' at the top but I have no idea what the reference should be otherwise.

Thanks!

**Comment by mandrean** [comment]
Hi @campbellC,

Good catch! I'd say it's a slip up from exporting a recording from Charles Proxy as a HAR, as you can see in the test fixture here: https://github.com/mandrean/har-rs/blob/master/tests/fixtures/someapi123.har#L5

I'll remove it and bump semver accordingly! Thanks.

**Comment by mandrean** [comment]
Sorry for the delay @campbellC. Busy summer!

Fixed in #14.
