### ISSUE TITLE
har-rs is trying to parse har file as yaml

### ISSUE THREAD

**Issue by Kalhama** [mandrean/har-rs#29]
Reading HAR fails with the error: `error: error serializing YAML`

I tried multiple webpages and it seems that some work.

Unfortunately I cannot post relevant .har file as it contains some personal information.

I noticed that in source code the har is parsed with serde_yaml though .har is json by spec (https://w3c.github.io/web-performance/specs/HAR/Overview.html#sec-har)

making pull request soon

Edit: Here is PR with fix https://github.com/mandrean/har-rs/pull/30

**Comment by ktis** [comment]
I got the same error when I read the har file I got from chrome. I applied a pull request and it solved the problem. Thanks!

**Comment by wgreenberg** [comment]
I also ran into this parsing a fairly typical HAR v1.2 file. Why is serde_yaml being used at all in this project? It'd be great to merge this and fix the issue.

**Comment by mandrean** [comment]
Thanks! Merged the fix.

**Comment by Kalhama** [comment]
Thanks
