### ISSUE TITLE
Support 1.3 draft?

### ISSUE THREAD

**Issue by rbtcollins** [mandrean/har-rs#3]
https://github.com/ahmadnassri/har-spec/blob/master/versions/1.3.md specifies some key fixes to HAR needed if one is dealing with binary APIs - e.g. GRPC.

Would be lovely to have that supported. What do you think?

**Comment by mandrean** [comment]
Nice! Yeah. Should be fairly simple to add. 🙌

**Comment by mandrean** [comment]
Ah, but the 1.3 proposal isn't an official draft but just a proposal by ahmadnassri, or am I mistaken?

**Comment by rbtcollins** [comment]
Its not entirely clear to me *what* it is; what is clear is that POST bodies with binary data are completely broken under 1.2, so I'd rather be able to opt-into an un-finalised thing than generate corrupt JSON :)

**Comment by rbtcollins** [comment]
Patch is up; if you like it, you could merge and push a release to crates? pretty please? :P.
There are other ergonomic things that could be done - e.g. storing the post body as a [u8] and auto setting the encoding and doing the base64 transparently etc; but just modelling whats there clearly is a pretty good start.

**Comment by mandrean** [comment]
Looks good! I added a small comment on #5.

**Comment by rbtcollins** [comment]
As this is merged, closing.
